/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/aside-menu/index.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HorizontalSquares: typeof import('./src/components/horizontal-squares/index.vue')['default']
    Qrcode: typeof import('./src/components/qrcode/index.vue')['default']
    QrcodeLogin: typeof import('./src/components/qrcode/QrcodeLogin.vue')['default']
    RecommendCard: typeof import('./src/components/recommend-card/index.vue')['default']
    RecommendedPlaylist: typeof import('./src/components/horizontal-squares/Recommended-Playlist.vue')['default']
    RecommendSinger: typeof import('./src/components/recommend-singer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterMenu: typeof import('./src/components/aside-menu/RouterMenu.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollLyric: typeof import('./src/components/scroll-lyric/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    VolumeBar: typeof import('./src/components/volume-bar/index.vue')['default']
  }
}
